version: '2.4'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
    image: elju-app:0.1.0
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes:
      - ./:/app/elju
      - vim-plug:/root/.vim/plugged
      - yarn-cache:/root/.yarn-cache
      - node-modules:/app/elju/node_modules
volumes:
  vim-plug:
  yarn-cache:
  node-modules:
